name: Publish distvae-tabular Package

on:
  push:
    tags:
      - 'v*.*.*'  # This matches version tags like v1.0.0, v2.1.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Configure Poetry
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config virtualenvs.create false
          poetry config pypi-token.pypi ${PYPI_TOKEN}

      - name: Install dependencies
        run: |
          poetry install --no-dev

      - name: Clean dist directory
        run: |
          rm -rf dist

      - name: Build package
        run: |
          poetry build

      - name: Publish package to PyPI
        run: |
          poetry publish --build
